/*eslint-disable */
const {readdir, writeFileSync, lstatSync} = require("fs");
const {join} = require("path")
const chalk = require("chalk")
const {spawn} = require('child_process')

const buildDir = join(__dirname, "..", "lib")
const indexFilePath = join(buildDir, "index.js")

// generating index file
readdir(buildDir, generateIndexFile);

// adding build directory
spawn('git', ['add', buildDir])

function generateIndexFile(err, files) {
  if (err) return console.log(err);
  const filteredFolder = files.filter(item => {
    let itemPath = join(buildDir, item)
    return (
      new RegExp(/^(?!.*images|styles).*$/g).test(item) &&
      lstatSync(itemPath).isDirectory()
    );
  });
  console.log("==========Components Builded=========");
  console.log(chalk.green(filteredFolder.join("\n")));
  console.log("=====================================");

  console.log("==========Creating Index File========");
  const indexFile = _createIndexFile(filteredFolder)
  console.log("==========Writing Index File=========");
  writeFileSync(indexFilePath, indexFile)
}

function _createIndexFile(files) {
  const fileString = `
  /***
   * Autogenerated file
   * Do not Change
   * This file is generated post build
   * */
  `
  const fileLines = files.map(v => `export { ${v} } from "./${v}"`)
  fileLines.unshift(fileString)
  fileLines.push('')
  return fileLines.join("\n")
}